/*
** EPITECH PROJECT, 2024
** inv
** File description:
** inv
*/
#include "../include/include.h"

gear_t all_gears[] = {
    {"Gueunilles", "Armor", 0, 1, 20, 0, 0, 0, 0, NULL, NULL,
        "Le Gougou du Gagak"},
    {"Armure en Cuir", "Armor", 5, 10, 5, 0, 0, 0, 0, NULL, NULL,
        "Le Gougou du Gagak"},
    {"Cotte de Mailles", "Armor", 0, 30, 10, 0, 0, 0, 0, NULL, NULL,
        "Le Gougou du Gagak"},
    {"Armure en Fer", "Armor", 0, 50, 0, 0, 0, 0, 0, NULL, NULL,
        "Le Gougou du Gagak"},
    {"Armure du Singe", "Armor", 15, 20, 50, 0, 0, 0, 0, NULL, NULL,
        "Le Gougou du Gagak"},
    {"Armure en Verre", "Armor", 15, 20, 50, 0, 0, 0, 0, NULL, NULL,
        "Le Gougou du Gagak"},
    {"Gillet pare-singe", "Armor", 0, 30, 15, 1, 1, 0, 0, NULL, &apply_poison,
        "Le Gougou du Gagak"},
    {"Veste du Business", "Armor", 0, 30, 40, 0, 0, 0, 0, NULL, NULL,
        "Le Gougou du Gagak"},
    {"Chemise du Touriste", "Armor", 20, 10, 30, 0, 0, 0, 0, NULL, NULL,
        "Le Gougou du Gagak"},
    {"Exosquelette du Futur", "Armor", 100, 100, 100, 1, 4, 1, 0,
        NULL, &apply_para, "Le Gougou du Gagak"},
    {"Baton", "Stun", 1, 0, 0, 1, 1, 0, 0, NULL, NULL,
        "Le Gougou du Gagak"},
    {"Marteau", "Stun", 100, 0, 0, 0, 0, 0, 0, NULL, NULL,
        "Le Gougou du Gagak"},
    {"MARTEAU EN MAJUSCULE", "Stun", 0, 0, 0, 0, 0, 0, 0, NULL, NULL,
        "Le Gougou du Gagak"},
    {"Bras de Fer", "Stun"
        , 40, 5, 5, 0, 0, 0, 0, NULL, NULL,
        "Le Gougou du Gagak"},
    {"Gantelet étoilé", "Stun", 40, 5, 5, 0, 0, 0, 0, NULL, &apply_para,
        "Le Gougou du Gagak"},
    {"Lance Pierre", "Range", 0, 0, 0, 0, 0, 0, 0, NULL, NULL,
        "Le Gougou du Gagak"},
    {"Epee en bois", "Slash", 0, 0, 0, 0, 0, 0, 0, NULL, NULL,
        "Le Gougou du Gagak"},
    {"Couteau bien bien sale", "Slash", 0, 0, 0, 0, 0, 0, 0, NULL, NULL,
        "Le Gougou du Gagak"},
    {"Grosse Epee", "Slash", 0, 0, 0, 0, 0, 0, 0, NULL, NULL,
        "Le Gougou du Gagak"},
    {"Epee encore plus grosse", "Slash", 0, 0, 0, 0, 0, 0, 0, NULL, NULL,
        "Le Gougou du Gagak"},
    {"Epee en Verre", "Slash", 0, 0, 0, 0, 0, 0, 0, NULL, NULL,
        "Le Gougou du Gagak"},
    {"Arc", "Range", 0, 0, 0, 0, 0, 0, 0, NULL, NULL,
        "Le Gougou du Gagak"},
    {"Railgun", "Range", 0, 0, 0, 0, 0, 0, 0, NULL, &apply_burn,
        "Le Gougou du Gagak"},
    {"Sarbacane du singe", "Range", 0, 0, 0, 0, 0, 0, 0,
        NULL, &apply_poison, "Le Gougou du Gagak"},
    {"Poing Mexicain", "Stun", 10, 0, 5, 25, 3, 1, 0,
        NULL, &apply_burn, "Le Gougou du Gagak"},
    {"Gun", "Range", 0, 0, 0, 0, 0, 0, 0, NULL, NULL,
        "Le Gougou du Gagak"},
    {"Boule de neige", "Spell", 5, 5, 0, 1, 1, 1, 0, NULL, &apply_frozen,
        "Le Gougou du Gagak"},
    {"Blizzard Eternel", "Spell", 50, 50, 0, 1, 3, 1, 0,
        NULL, &apply_frozen, "Le Gougou du Gagak"},
    {"Voile de Glace", "Spell", 0, 0, 0, 0, 0, 1, 0, NULL, &def_buff,
        "Le Gougou du Gagak"},
    {"Bouclier de Glace", "Spell", 0, 0, 0, 0, 0, 1, 0, NULL, &def_buff,
        "Le Gougou du Gagak"},
    {"Muraille de Glace", "Spell", 0, 0, 0, 0, 0, 1, 0, NULL, &def_buff,
        "Le Gougou du Gagak"},
    {"Zap", "Spell", 10, 0, 0, 0, 0, 1, 0, NULL, &apply_para,
        "Le Gougou du Gagak"},
    {"Canon de Foudre", "Spell", 0, 0, 0, 0, 0, 1, 0, NULL, &apply_para,
        "Le Gougou du Gagak"},
    {"Éclair Magique", "Spell", 0, 0, 0, 0, 0, 1, 0, NULL, &apply_para,
        "Magie tout de suite"},

    {"Boule de feu", "Spell", 0, 0, 0, 0, 0, 1, 0, NULL, &apply_burn,
        "Le Gougou du Gagak"},
    {"Canon de Flammes", "Spell", 0, 0, 0, 0, 0, 1, 0, NULL, &apply_burn,
        "Le Gougou du Gagak"},
    {"Tornade de Feu", "Spell", 0, 0, 0, 0, 0, 1, 0, NULL, &apply_burn,
        "Le Gougou du Gagak"},

    {"Tu préfères", "Spell", 0, 0, 0, 0, 0, 1, 0, NULL, NULL,
        "Tu préfères le soleil ou bien la pluie"},
    {"Comète filante", "Spell", 0, 0, 0, 0, 0, 0, 0, NULL, &heal,
        "FAIS UN VOEU"},
    {"Météore Géant", "Spell", 0, 0, 0, 30, 3, 1, 0, NULL, &apply_burn,
        "Fait descendre un météore sur le terrain"},
    {"Vanne dann croisée", "Spell", 0, 0, 0, 20, 0, 1, 0, NULL, &apply_poison,
        "Aie aie aie, le sort"},
    {NULL, NULL, 0, 0, 0, 0, 0, 0, 0, NULL, NULL, "Le Gougou du Gagak"},
};

item_t all_items[] = {
    {"Pomme", "Soin : ", 10, 1, 0, 0, NULL, &heal, "TEMPLATE"},
    {"Potion de Vie", "Armor", 50, 1, 0, 0, NULL, &heal, "TEMPLATE"},
    {"Potion Sucrée et Torsique", "Soin : ", 50, 3, 0, 0, NULL, &heal,
        "TEMPLATE"},
    {"Tacos 3 viandes (Poulet)", "Armor", 75, 30, 0, 0,
        NULL, &heal_percent, "TEMPLATE"},
    {"Pastèque", "Armor", 50, 1, 0, 0,
        NULL, &heal_percent, "TEMPLATE"},
    {"La Meilleure Pastèque", "Armor", 100, 1, 0, 0, NULL, &heal_percent,
        "TEMPLATE"},
    {"Potion de Magie", "Soin : ", 5, 10, 0, 0, NULL, &reco_mana,
        "TEMPLATE"},
    {"Dakatine", "Soin : ", 50, 1, 0, 0, NULL, &reco_mana, "TEMPLATE"},
    {"Mangue", "Armor", 50, 1, 0, 0,
        NULL, &reco_mana_percent, "TEMPLATE"},
    {"La Meilleure Mangue", "Armor", 100, 1, 0, 0, NULL, &reco_mana_percent,
        "TEMPLATE"},
    {"Banane Braisée au Sel", "Lancer", 5, 5, 0, 1, NULL, &apply_para,
        "TEMPLATE"},
    {"Queue du Singe", "Armor", 40, 3, 0, 0, NULL, &atk_buff,
        "Vous avez bouffé un bout de singe"},
    {"Poison To-Chane", "Armor", 5, 0, 0, 1, NULL, &apply_para, ""},
    {"Super Poison du To-Chane", "Armor", 2, 0, 0, 1, NULL, &apply_poison,
        "TEMPLATE"},
    {"Poisson Cru", "Soin : ", 25, 1, 0, 0,
        NULL, &heal_percent, "TEMPLATE"},
    {"Poisson Cuit", "Soin : ", 60, 0, 0, 0,
        NULL, &heal_percent, "TEMPLATE"},
    {"Parchemin du Gel", "Status", 5, 2, 0, 1,
        NULL, &apply_frozen, "TEMPLATE"},
    {"Parchemin des Flammes", "Status", 10, 5, 0, 1,
        NULL, &apply_burn, "TEMPLATE"},
    {"Parchemin de la Foudre", "Status", 5, 6, 0, 1,
        NULL, &apply_para, "TEMPLATE"},
    {"Parchemin de Pestilence", "Status", 3, 5, 0, 1,
        NULL, &apply_poison, "TEMPLATE"},
    {"Parchemin Revitalisant", "Status", 20, 3, 0, 1,
        NULL, &heal_percent, "TEMPLATE"},
    {"Glaçon Chaud", "Status", 5, 2, 0, 1,
        NULL, &freeze_or_burn, "TEMPLATE"},
    {"Monster", "Soin : ", 50, 3, 0, 0, NULL, &atk_buff, "TEMPLATE"},
    {"Bonbon à la pêche", "Armor", 2, 30, 0, 1
        , NULL, &apply_poison,
        "C'est bon les bonbons mais ça donne la peste"},
    {NULL, NULL, 0, 0, 0, 0, NULL, NULL, NULL}
};
